---
- name: Install Prezto
  git: repo=https://github.com/sorin-ionescu/prezto.git dest=~/.zprezto force=yes

- name: Symlink my dotfiles
  file: src=~/dotfiles/home/{{ item }}
        dest=~/{{ item }}
        state=link
        force=yes
  with_items:
    - .vimrc
    - .zshrc
    - .zpreztorc
    - .zlogin
    - .zlogout
    - .zshenv
    - .inputrc
    - .gemrc
    - .gitignore
    - .gitconfig
    - .ubervu.sh
    - .pythonrc
    - .tmux.conf

- name: Clone Vundle
  git: repo=https://github.com/gmarik/Vundle.vim.git dest=~/.vim/bundle/Vundle.vim

- name: Install/update VIM plugins
  command: vim +PluginInstall! +qall
