---
- name: Install libraries using APT
  apt: name={{ item }} state=latest
  sudo: true
  with_items:
    - ack-grep
    - bash
    - curl
    - git
    - htop
    - nmap
    - node
    - most
    - python
    - python-pip
    # for FASD
    - python-pycurl
    - python3
    - vim
    - wget
    - zsh

- name: Change shell to ZSH
  user: shell=/bin/zsh name={{ ansible_ssh_user }}

- name: Install FASD
  copy: src=fasd dest=/usr/local/bin/fasd mode=755
