---
- name: Install python-pycurl for fasd
  apt: name=python-pycurl state=present

- name: Install libraries using APT
  apt: name={{ item }} state=latest
  with_items:
    - ack-grep
    - bash
    - curl
    - git
    - nmap
    - node
    - most
    - python
    - python-pip
    - python3
    - vim
    - wget
    - zsh

- name: Change shell to ZSH
  user: shell=/bin/zsh name={{ ansible_ssh_user }}

- name: Install FASD
  copy: src=fasd dest=/usr/local/bin/fasd mode=755
