---
- name: Update Homebrew
  homebrew: update_homebrew=yes

- name: Install libraries with Homebrew
  homebrew: name={{ item }} state=latest
  with_items:
    - ack
    - curl
    - fasd
    - git
    - hub
    - nmap
    - node
    - python
    - python3
    - readline
    - rename
    - ssh-copy-id
    - vim
    - watch
    - wget
    - zsh
    - httpie
    - tree
    - openssl

- name: Tap into the Homebrew Cask Beta apps
  homebrew_tap: tap=caskroom/versions state=present

- name: Install libraries with Homebrew Cask
  homebrew_cask: name={{ item }} state=present
  with_items:
    - dropbox
    - evernote
    - google-chrome
    - iterm2
    - sublime-text3
    - hipchat
    - viber
    - github
    - spotify
    - macpass
    - virtualbox
    - trailer
    - spotifree
    - skitch
    - flux
    - sequel-pro
    - vagrant
    - xmarks-safari
    - vagrant-manager
    - utorrent
    - vlc
    - menumeters
    - clipmenu
    - bartender

- name: Cleanup Brew packages
  command: brew cleanup

- name: Cleanup Brew Cask packages
  command: brew cask cleanup
