---
- name: Update Homebrew
  homebrew: update_homebrew=yes

- name: Install libraries with Homebrew
  homebrew: name={{ item }} state=latest
  with_items:
    - ack
    - curl
    - fasd
    - git
    - hub
    - nmap
    - node
    - python
    - python3
    - readline
    - rename
    - ssh-copy-id
    - vim
    - watch
    - wget
    - zsh
    - httpie
    - tree
    - openssl
    - cask
    - coreutils
    - findutils
    - mosh
    - brew-cask
    - youtube-dl

- name: Cleanup Brew packages
  command: brew cleanup
