- hosts: targets
  tasks:
    - group_by: key={{ ansible_distribution }}

- hosts: MacOSX
  gather_facts: False
  tasks:
    - include: tasks/mac.yml
    - include: tasks/dotfiles.yml
    - include: tasks/pip.yml
    - include: tasks/update_repos.yml

- hosts: Ubuntu
  gather_facts: False
  tasks:
    - include: tasks/ubuntu.yml
    - include: tasks/dotfiles.yml
    - include: tasks/pip.yml
